apiVersion: apps/v1
kind: Deployment
metadata:
  name: meudeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      version: v1
  template:
    metadata:
      labels:
        version: v1
    spec:
      containers:
      - name: web-app
        image: ggodoi1986/conversao-temperatura:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:  
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    version: v1
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000
  type: NodePort
    
